--- #YAML:1.0
name:                Bundle-OpenXPKI
version:             0.04
abstract:            A bundle to install modules required for OpenXPKI
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.32
distribution_type:   module
requires:     
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Alexander Klink <alech@cpan.org>
